Feature: Manage Batches(Admin) Page

#Background: Admin is logged in and Programs were created
	
#Feature: Add Batch by Admin (Modified - Different Batches function Performed by Admin)
	Scenario: Check whether Admin can add batch to batches list
    Given Admin is on Add tab of ADD/Edit batches page (admin) by clicking on Add Batch in Manage Batches Page(admin) 
    When Admin clicks on submit button after entering Batch Name, Batch Description,select Batch Status, enters BatchNo. of classes.
    Then Created Batch details will be displayed in Manage Batches Page(Admin)   with auto generated Created Date and Modified date in MM/DD/YY format.
	
#Background: Admin is logged in, Programs and Batches were created already (modified - Admin is logged in and Programs were created)
#Feature: Edit Batch by Admin (Modified - Different Batches function Performed by Admin)

Scenario: Check whether Admin can edit particular batch in batches list
    Given Admin is on Edit tab of ADD/Edit batches page (admin) by clicking on edit icon
    When Admin clicks on submit button after updating Batch Name, Batch Description,select Batch Status, Baych No. of classes
    Then Updated Batch details will be displayed in Manage Batches Page(Admin) screen   with same autogenerated creation date and  different Modified date in MM/DD/YY format
          
 #Feature: Delete Batch by Admin (Modified - Different Batches function Performed by Admin)
 
 Scenario: Check whether Admin can delete particular batch in batches list 
    Given Admin is on Manage Batches Page(admin) screen
    When Admin clicks on particular batch trash icon
    Then Batch will be deleted from the Batches List in Manage Batches Page(admin)
 




